[env:m5stack-core-esp32]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified@^0.2.2
    meganetaaan/M5Stack-Avatar@^0.10.0
    bblanchon/ArduinoJson
    witnessmenow/UniversalTelegramBot
